import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen bg-black`}
      >
        <header>
          <h1 className="text-6xl font-extrabold text-blue-900 px-12">NOMAD MOVIES</h1>
        </header>
        <main className="w-screen min-h-screen">{children}</main>
        <footer className="w-full h-1/12">
          <p className="w-full text-center p-4">
            All the resources belong to
            &copy;https://nomad-movies.nomadcoders.workers.dev/
          </p>
        </footer>
      </body>
    </html>
  );
}
