import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen bg-black`}
      >

        {children}
        <footer className="w-full h-1/12 bg-black">

          <p className="w-full text-center text-white p-4">All the resources belong to &copy;https://nomad-movies.nomadcoders.workers.dev/</p>
        </footer>
      </body>
    </html>
  );
}
